# Generated by Django 3.2.25 on 2024-07-20 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20240720_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='workimages')),
                ('appointed', models.ManyToManyField(related_name='appointed_works', to=settings.AUTH_USER_MODEL)),
                ('appointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointer_works', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.workstatus')),
            ],
        ),
    ]
