# Generated by Django 3.2.25 on 2024-07-22 08:08

from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20240721_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.ForeignKey(default=members.models.default_work_status, on_delete=django.db.models.deletion.CASCADE, to='members.workstatus'),
        ),
    ]
