# Generated by Django 3.2.25 on 2024-07-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='relatedWork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.work'),
        ),
    ]
