# Generated by Django 3.2.25 on 2024-07-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_work_relatedwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.role'),
        ),
    ]
